[package]
name = "eseek-archive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-lzma = "0.6.0"
flatbuffers = "24.3.25"
